# FILE: .github/workflows/ci.yml

name: Simulate Deployment and Trigger Correlator

on:
  push:
    branches: [ "main" ]

jobs:
  # We only need one simple job now.
  fire-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: "Announce deployment"
        run: echo "Simulating deployment of commit ${{ github.sha }} for repo ${{ github.repository }}"

      - name: "Fire Webhook to Correlator"
        run: |
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Suspicious user activity detected"
          }' "${{ github.repository }}" "${{ github.sha }}")

          curl -sf -X POST "${{ secrets.CORRELATOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"