# In .github/workflows/ci.yml

      - name: "Fire Webhook to Correlator"
        # This version is more robust against shell parsing errors.
        run: |
          # Prepare the JSON payload, escaping quotes.
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Command Injection Vulnerability Scan"
          }' "${{ github.repository }}" "${{ github.sha }}")

          # Send the webhook. -s for silent, -f to fail on server errors.
          curl -sf -X POST "${{ secrets.CORRELATOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"