# FILE: .github/workflows/ci.yml

# Name for the entire workflow, displayed on GitHub's Actions tab.
name: Build CodeQL DB, Deploy, and Trigger Correlator

# Trigger this workflow on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This job's only purpose is to build the CodeQL database.
  build-codeql-database:
    # The type of virtual machine the job will run on.
    runs-on: ubuntu-latest
    # Define the permissions the GITHUB_TOKEN will have for this job.
    permissions:
      security-events: write # Required for CodeQL to upload results to GitHub
      actions: read        # Required for the CodeQL action to read metadata

    # A job contains a sequence of tasks called steps.
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        id: codeql-init
        uses: github/codeql-action/init@v3
        with:
          languages: python
          
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Move CodeQL database to a known path
        run: mv ${{ runner.temp }}/codeql_databases/python ./codeql-db
        
      # Step 4: Upload the database artifact from the known, non-relative path
      - name: Upload CodeQL database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-db-for-${{ github.sha }}
          path: ./codeql-db  



  # This job simulates a deployment and sends the webhook.
  simulate-deploy-and-trigger:
    # This job will only start after 'build-codeql-database' completes successfully.
    needs: build-codeql-database
    runs-on: ubuntu-latest

    steps:
      # This job doesn't need to check out the code again. We just fire the webhook.
      - name: "Fire Webhook to Correlator"
        run: |
          # Prepare the JSON payload safely.
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Suspicious user activity detected"
          }' "${{ github.repository }}" "${{ github.sha }}")

          # Send the webhook.
          curl -sf -X POST "${{ secrets.CORRELOTOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"