# FILE: .github/workflows/ci.yml

name: Build CodeQL DB, Deploy, and Trigger Correlator

on:
  push:
    branches: [ "main" ]

jobs:
  # --- NEW JOB: This job's only purpose is to build the CodeQL database ---
  build-codeql-database:
    runs-on: ubuntu-latest
    permissions:
      # Required for the CodeQL Action to initialize and analyze
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use GitHub's official CodeQL Action to initialize the analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python # Specify the language of your repository
          # We don't run the analysis here, we just build the database.

      # This step would be where you build/test your actual application.
      # For our simple Python app, we can just install dependencies.
      - name: "Build/Test Application (Simulated)"
        run: pip install -r requirements.txt
        
      # This action finalizes the database creation.
      - name: Finalize CodeQL Database
        uses: github/codeql-action/finalize-database@v2

      # CRITICAL STEP: Upload the generated CodeQL database as a workflow artifact.
      # This makes the database available for other jobs or for download.
      - name: Upload CodeQL database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-db-for-${{ github.sha }} # Name the artifact with the commit hash
          path: ${{ runner.temp }}/codeql_databases # Default path where the DB is created


  # --- MODIFIED JOB: This job now depends on the build job ---
  simulate-deploy-and-trigger:
    # This job will only run after 'build-codeql-database' completes successfully
    needs: build-codeql-database
    runs-on: ubuntu-latest

    steps:
      # No need to check out the code again. We just need to fire the webhook.
      - name: "Fire Webhook to Correlator"
        run: |
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Suspicious user activity detected"
          }' "${{ github.repository }}" "${{ github.sha }}")

          curl -sf -X POST "${{ secrets.CORRELATOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"