# FILE: .github/workflows/ci.yml

# Name for the entire workflow, displayed on GitHub's Actions tab.
name: Build CodeQL DB, Deploy, and Trigger Correlator

# Trigger this workflow on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs.
jobs:
  # This job's purpose is to build the CodeQL database for the pushed commit.
  build-codeql-database:
    # The type of virtual machine the job will run on.
    runs-on: ubuntu-latest
    
    # Define the permissions the GITHUB_TOKEN will have for this job.
    permissions:
      security-events: write # Required for CodeQL to initialize.
      actions: read        # Required for the CodeQL action to read metadata.
      contents: read       # Required for actions/checkout.

    # A job contains a sequence of tasks called steps.
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE.
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest stable version

      # Step 2: Initializes the CodeQL tools for scanning (using the non-deprecated v3).
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Step 3: Automatically builds the CodeQL database.
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Step 4: Move the created database to a predictable local path for upload.
      - name: Move CodeQL database to a known path
        run: mv ${{ runner.temp }}/codeql_databases/python ./codeql-db

      # Step 5: Uploads the generated CodeQL database as a workflow artifact.
      - name: Upload CodeQL database as artifact
        uses: actions/upload-artifact@v4 # Use the latest stable version
        with:
          name: codeql-db-for-${{ github.sha }}
          path: ./codeql-db
          retention-days: 7 # Keep artifacts for 7 days.

  # This job simulates a deployment and sends the webhook.
  simulate-deploy-and-trigger:
    # This job will only start after 'build-codeql-database' completes successfully.
    needs: build-codeql-database
    runs-on: ubuntu-latest

    steps:
      # This job fires the webhook with the commit and repository info.
      - name: "Fire Webhook to Correlator"
        run: |
          # Prepare the JSON payload safely to avoid shell parsing issues.
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Suspicious user activity detected"
          }' "${{ github.repository }}" "${{ github.sha }}")

          # Send the webhook.
          # -s makes it silent.
          # -f makes it fail with an error code if the server returns an HTTP error.
          curl -sf -X POST "${{ secrets.CORRELATOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"