# FILE: .github/workflows/ci.yml

name: Build CodeQL DB, Deploy, and Trigger Correlator

on:
  push:
    branches: [ "main" ]

jobs:
  # This job builds the CodeQL database and uploads it as an artifact.
  build-codeql-database:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initialize the CodeQL Action (v3)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Autobuild the database
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Move the created database to a predictable local path
      - name: Move CodeQL database to a known path
        run: mv ${{ runner.temp }}/codeql_databases/python ./codeql-db

      # Upload the database from that known path
      - name: Upload CodeQL database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-db-for-${{ github.sha }}
          path: ./codeql-db

  # This job simulates a deployment and sends the webhook.
  simulate-deploy-and-trigger:
    needs: build-code-database # Corrected job name
    runs-on: ubuntu-latest

    steps:
      # This job doesn't need to check out the code again.
      - name: "Fire Webhook to Correlator"
        run: |
          # Prepare the JSON payload safely.
          JSON_PAYLOAD=$(printf '{
            "service_name": "%s",
            "commit_hash": "%s",
            "alert_summary": "Suspicious user activity detected"
          }' "${{ github.repository }}" "${{ github.sha }}")

          # Send the webhook.
          # -s makes it silent.
          # -f makes it fail with an error code if the server returns an HTTP error.
          curl -sf -X POST "${{ secrets.CORRELATOR_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Webhook" \
          -d "$JSON_PAYLOAD"